[package]
name = "kernel32"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
common = { path = "../common" }
log = { workspace = true }
windows-sys = { workspace = true }
