[package]
name = "unicorn_poc"
version = "0.1.0"
edition = "2024"

[dependencies]
unicorn-engine = "2.1.3"
hex = "0.4"
object = "0.37.3"
anyhow = "1.0.99"
iced-x86 = "1.21.0"
log = "0.4"
fast_log = { version = "1.7" }
once_cell = "1.20"
