[package]
name = "win64-emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
# emulation
unicorn-engine = "2.1.3"
# pe64
object = "0.37.3"
# disassembly
iced-x86 = "1.21.0"
# logging
log = "0.4"
fast_log = { version = "1.7" }
